### PR TITLE
Create strings.xml - polish translation

### PR DESCRIPTION
**Pull request by phyrz91**

### CODE REVIEW

**Comment by woheller69** [comment]
thanks. Maybe you want to test and translate this app as well. I am mainly working on this one. It uses a free API.

https://github.com/woheller69/omweather

**Comment by phyrz91** [comment]
When I find some time. :

**Comment by phyrz91** [comment]
Done. What is the difference between one application and another?  Try to add application icons in the "monet" standard.

**Comment by woheller69** [comment]
main difference is the different API. Open-Meteo does not require an API key

**Pull request merged**
