### PR TITLE
Add italian language

### PR DESCRIPTION
**Pull request by Stenafo**

### CODE REVIEW

**Comment by woheller69** [comment]
can you please also add an it-IT directory here:

https://github.com/Stenafo/weather/tree/main/fastlane/metadata/android

and translate the 2 descriptions (like in the es-ES folder)? That is needed for F-Droid.

**Comment by woheller69** [comment]
and strings.xml must be moved to a new folder values-it in res

**Comment by Stenafo** [comment]
Is it okay? Sorry but I'm not practical hahah

**Comment by woheller69** [comment]
Almost. In the fastlane folder where you added title.txt we also need the short and long descriptions translated

**Pull request merged**
