### PR TITLE
Russian translation improvements

### PR DESCRIPTION
**Pull request by solokot**
Mostly auto-translation fixes and minor stylistic improvements.

### CODE REVIEW

**Comment by woheller69** [comment]
Thanks! I will look into it and include it in one of the next releases

**Comment by woheller69** [comment]
There are 2 more strings I will probably need in future:
1) Search locations via Photon API or internal city list: 
Поиск местоположений через Photon API или внутренний список городов 

2) Internal city list:
Список внутренних городов

Is this ok?

**Comment by solokot** [comment]
1 - This is ok
2 - But here is a classic machine translation error: instead of an "internal city list" translated "list of internal cities". This is a very common Google translation mistake for the Russian language (the fact that the translation is wrong can be easily verified via reverse translation). Correctly it will be like this: "Внутренний список городов".

**Comment by woheller69** [comment]
👍

**Comment by woheller69** [comment]
one more thing:
For better search results please activate online search via photon API in settings
Для улучшения результатов поиска активируйте онлайн-поиск через Photon API в настройках.

**Comment by solokot** [comment]
This is ok

**Comment by woheller69** [comment]
Just added a new option to choose if  temperatures shall be shown with one decimal place (or without decimal).
Is this ok?

  <string name="settings_temp_decimal">отображение температуры с одним десятичным знаком </string>

  <string name="settings_temp_decimal">Show temperature with one decimal</string>

**Comment by solokot** [comment]
Показывать температуру с десятыми долями
will be slightly better

**Comment by woheller69** [comment]
Included in V3.0

**Pull request closed without merging**
