### PR TITLE
stenafo italian patch

### PR DESCRIPTION
**Pull request by Stenafo**
Improved some translations.

### CODE REVIEW

**Comment by woheller69** [comment]
There are some new strings in strings.xml and also changes in description due to the new GPS feature. Can you please include that as well?

**Comment by woheller69** [comment]
please fetch current upstream first and then modify

**Comment by Stenafo** [comment]
Hi, I'm sorry but during the month I had a lot of commitments and I couldn't correct the error.
Should I just add line 144 on strings.xml?

**Comment by woheller69** [comment]
Then just take my latest strings.xml, make your changes and upload the file here

**Pull request closed without merging**
