### PR TITLE
Turkish lang support

### PR DESCRIPTION
**Pull request by ondern**
Fully completed

### CODE REVIEW

**Comment by woheller69** [comment]
Have you tried my omWeather? Maybe you want to translate it too

**Comment by ondern** [comment]
> Have you tried my omWeather? Maybe you want to translate it too

I will

**Comment by ondern** [comment]
@woheller69 Translation has been completed. Kindly ask you merge in main repo

**Comment by ondern** [comment]
@woheller69

**Comment by woheller69** [comment]
Then you should not close it...
Please reopen, when really finished

**Comment by ondern** [comment]
Fully completed

**Comment by woheller69** [comment]
You need to remove the COMPLETE strings which contain 

translatable="false"

**Comment by ondern** [comment]
@woheller69

**Pull request merged**
